name: Module-3 Assignment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test | tee test-results.txt  

      - name: Upload test results as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.txt

  deploy:
    needs: test
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download test results artifact
        uses: actions/download-artifact@v4
        with:
          name: test-results

      - name: Show test results
        run: cat test-results.txt

      - name: Install dependencies
        run: npm install

      - name: Run the application by PM2
        run: |
          ls -a
          pm2 status
          pm2 delete node-app || true
          pm2 start "npm start" --name "node-app"
          pm2 save