name: Module-3 Assignment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run check 

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create artifacts
        run: |
            mkdir -p build  
            echo "hello world" > build/hello.txt  
            
      - name: Upload artifact 
        uses: actions/upload-artifact@v4
        with:
            name: build_folder
            path: ./build


  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Receive artifacts
        uses: actions/download-artifact@v4
        with:
          name: build_folder
        
      - name: Show the artifacts
        run: |
          ls -a

      - name: Install dependencies
        run: npm install

      - name: Run the application by PM2
        run: |
          ls -a
          pm2 status
          pm2 delete node-app || true
          pm2 start "npm start" --name "node-app"
          pm2 save
